//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.13.1
//     from Assets/ControladoreControladores_Movimientos/Movimientos_Peleador.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/ControladoreControladores_Movimientos/Movimientos_Peleador.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Movimientos_Peleador: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Movimientos_Peleador()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Movimientos_Peleador"",
    ""maps"": [
        {
            ""name"": ""Jugador1"",
            ""id"": ""f81ccbf2-52a8-4862-a200-9e13c6c14b8f"",
            ""actions"": [
                {
                    ""name"": ""Mover"",
                    ""type"": ""Value"",
                    ""id"": ""3d7785c0-de0b-4fdc-9aca-46bd299f8501"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""020f68a0-a9bf-4cc5-b9f8-736ccbcb3983"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe Gancho Arriba"",
                    ""type"": ""Button"",
                    ""id"": ""24a962d7-0d06-4669-bdb4-e20a57f8be6c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe Bajo"",
                    ""type"": ""Button"",
                    ""id"": ""0301f9a4-9c5a-4ffe-9992-29badb4289a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bloquear"",
                    ""type"": ""Button"",
                    ""id"": ""cfeafa15-f380-41fa-a5fd-596726de88d0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada Voladora Combo"",
                    ""type"": ""Button"",
                    ""id"": ""fc68f651-4c66-4bfd-ac08-c1aa47a28f6c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada con Salto"",
                    ""type"": ""Button"",
                    ""id"": ""5cfe646c-16a5-4f3d-9d81-7c208ee13622"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Amague y Patada"",
                    ""type"": ""Button"",
                    ""id"": ""2e620e96-194b-4d1d-857b-713e0aa909b7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Amague y Patada Avanzada"",
                    ""type"": ""Button"",
                    ""id"": ""dec7d6d0-7ab5-459f-9a44-1d2ac605be4d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada a la Cabeza"",
                    ""type"": ""Button"",
                    ""id"": ""b7a12c2d-bf51-4466-9b75-cf45f04c71c0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gancho Derecho"",
                    ""type"": ""Button"",
                    ""id"": ""aff70a50-9f97-4065-bd2e-eeb4e7b56791"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpes de Rodilla Combo"",
                    ""type"": ""Button"",
                    ""id"": ""ab3d6024-c25f-4075-8301-c137ffe3a9ed"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fireball"",
                    ""type"": ""Button"",
                    ""id"": ""d378a1d1-0316-4b4e-864e-98e27f1129e1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""215b9eb3-f99f-4c0c-af7d-070019cef3dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""46b0f6a1-0e02-46ab-8ca8-39c9dd26173c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""de91bd3e-3e02-4f88-9d60-38a093d8642a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8653b6a4-efb5-4151-b02d-394b8599a904"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c826b60e-cca3-4b28-bc56-56282f9d7e62"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c58e10ec-4a07-4c44-b874-4e768c53b8db"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7d23d6a-c712-4d85-a3e5-d71422cade9c"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe Gancho Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""545820c6-a07a-471d-a93b-a9e2dab59a78"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe Bajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ae2a01a-36f9-4615-8481-cc8a3fc4fc87"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bloquear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d31029a-8fbd-4141-b769-4e7ae4064160"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada Voladora Combo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc71f99d-5161-4a9d-a97b-276299c8fde0"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada con Salto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66b229db-0b00-4e85-b9ac-e5df7070a5b0"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Amague y Patada"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fbc1683-3537-451f-93ee-c45d386de89a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Amague y Patada Avanzada"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e445e90c-d518-42f7-8882-38a2930217b2"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada a la Cabeza"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ad77904-bfd4-45d8-b48a-012f8c9575b8"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gancho Derecho"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baf59265-8d2f-446d-93f5-7f7941fe8123"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpes de Rodilla Combo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99a58019-fa68-4a8a-a31f-95e04f347c98"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Jugador2"",
            ""id"": ""58c22914-e319-4fa1-acc2-ab098645b591"",
            ""actions"": [
                {
                    ""name"": ""Mover"",
                    ""type"": ""Value"",
                    ""id"": ""e2796c1b-1291-46a8-ad09-30628ea8cf40"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Saltar"",
                    ""type"": ""Button"",
                    ""id"": ""11220d80-ef1f-4156-b63e-a34d3b1f557d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe Gancho Arriba"",
                    ""type"": ""Button"",
                    ""id"": ""45e48d9a-7b31-471b-b1c0-7d3762e330a1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpe Bajo"",
                    ""type"": ""Button"",
                    ""id"": ""4a4518eb-9163-4897-9278-547bd6caf3e8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Bloquear"",
                    ""type"": ""Button"",
                    ""id"": ""96ee3ab7-de33-4f06-83fd-4f5fcdff97a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada Voladora Combo"",
                    ""type"": ""Button"",
                    ""id"": ""49b478ea-9859-471b-8888-c01922c235cf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada con Salto"",
                    ""type"": ""Button"",
                    ""id"": ""2f7b8044-9c3c-42e8-a782-bbd9b3a0f0d3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Amague y Patada"",
                    ""type"": ""Button"",
                    ""id"": ""0ec8d725-64d4-42a7-b97e-9ba21ba95209"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Amague y Patada Avanzada"",
                    ""type"": ""Button"",
                    ""id"": ""5d32929f-4703-4522-b5af-2de6b81505bf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Patada a la Cabeza"",
                    ""type"": ""Button"",
                    ""id"": ""98a3df42-1760-424f-a4d1-fb3e5cdbc1e9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Gancho Derecho"",
                    ""type"": ""Button"",
                    ""id"": ""cc392499-c4ce-40b7-ae96-cee216961a8e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Golpes de Rodilla Combo"",
                    ""type"": ""Button"",
                    ""id"": ""cdd7db77-29b3-46f4-b665-6a8a427713bb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fireball"",
                    ""type"": ""Button"",
                    ""id"": ""8bfafc62-3cf9-42b4-95ff-043e9c1ff54e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""fa05490d-489b-424b-a6ed-c2e76069beb3"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ab53000-0c79-4581-8350-22e1959bb799"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Saltar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0684f20-9234-4360-971c-d420a97203d8"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe Gancho Arriba"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03a3b027-4ebf-4592-8114-af17bc5c1c70"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpe Bajo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""535de968-e2c3-4ee0-94db-6f0d6aa2ab72"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Bloquear"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""927a8b8d-a643-4bf9-ba25-b81c1d3e54a4"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada Voladora Combo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72ade50b-8871-464f-8d89-0378b8fa62a6"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada con Salto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""899f24ff-fa1b-4335-a1bf-17c40148d292"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Amague y Patada"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52182a7c-b6a6-4590-a695-65ba7a24692f"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Amague y Patada Avanzada"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f987cc0a-4267-4e40-b142-be62f89f13a2"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Patada a la Cabeza"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31853fc8-87f4-47d6-a0da-65eabf15ff2d"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Gancho Derecho"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""690c2b8b-19aa-4a2f-aae7-5f345be20add"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Golpes de Rodilla Combo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ccb0981d-f753-48f6-a8ab-ad8f0cd3437b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fireball"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jugador1
        m_Jugador1 = asset.FindActionMap("Jugador1", throwIfNotFound: true);
        m_Jugador1_Mover = m_Jugador1.FindAction("Mover", throwIfNotFound: true);
        m_Jugador1_Saltar = m_Jugador1.FindAction("Saltar", throwIfNotFound: true);
        m_Jugador1_GolpeGanchoArriba = m_Jugador1.FindAction("Golpe Gancho Arriba", throwIfNotFound: true);
        m_Jugador1_GolpeBajo = m_Jugador1.FindAction("Golpe Bajo", throwIfNotFound: true);
        m_Jugador1_Bloquear = m_Jugador1.FindAction("Bloquear", throwIfNotFound: true);
        m_Jugador1_PatadaVoladoraCombo = m_Jugador1.FindAction("Patada Voladora Combo", throwIfNotFound: true);
        m_Jugador1_PatadaconSalto = m_Jugador1.FindAction("Patada con Salto", throwIfNotFound: true);
        m_Jugador1_AmagueyPatada = m_Jugador1.FindAction("Amague y Patada", throwIfNotFound: true);
        m_Jugador1_AmagueyPatadaAvanzada = m_Jugador1.FindAction("Amague y Patada Avanzada", throwIfNotFound: true);
        m_Jugador1_PatadaalaCabeza = m_Jugador1.FindAction("Patada a la Cabeza", throwIfNotFound: true);
        m_Jugador1_GanchoDerecho = m_Jugador1.FindAction("Gancho Derecho", throwIfNotFound: true);
        m_Jugador1_GolpesdeRodillaCombo = m_Jugador1.FindAction("Golpes de Rodilla Combo", throwIfNotFound: true);
        m_Jugador1_Fireball = m_Jugador1.FindAction("Fireball", throwIfNotFound: true);
        // Jugador2
        m_Jugador2 = asset.FindActionMap("Jugador2", throwIfNotFound: true);
        m_Jugador2_Mover = m_Jugador2.FindAction("Mover", throwIfNotFound: true);
        m_Jugador2_Saltar = m_Jugador2.FindAction("Saltar", throwIfNotFound: true);
        m_Jugador2_GolpeGanchoArriba = m_Jugador2.FindAction("Golpe Gancho Arriba", throwIfNotFound: true);
        m_Jugador2_GolpeBajo = m_Jugador2.FindAction("Golpe Bajo", throwIfNotFound: true);
        m_Jugador2_Bloquear = m_Jugador2.FindAction("Bloquear", throwIfNotFound: true);
        m_Jugador2_PatadaVoladoraCombo = m_Jugador2.FindAction("Patada Voladora Combo", throwIfNotFound: true);
        m_Jugador2_PatadaconSalto = m_Jugador2.FindAction("Patada con Salto", throwIfNotFound: true);
        m_Jugador2_AmagueyPatada = m_Jugador2.FindAction("Amague y Patada", throwIfNotFound: true);
        m_Jugador2_AmagueyPatadaAvanzada = m_Jugador2.FindAction("Amague y Patada Avanzada", throwIfNotFound: true);
        m_Jugador2_PatadaalaCabeza = m_Jugador2.FindAction("Patada a la Cabeza", throwIfNotFound: true);
        m_Jugador2_GanchoDerecho = m_Jugador2.FindAction("Gancho Derecho", throwIfNotFound: true);
        m_Jugador2_GolpesdeRodillaCombo = m_Jugador2.FindAction("Golpes de Rodilla Combo", throwIfNotFound: true);
        m_Jugador2_Fireball = m_Jugador2.FindAction("Fireball", throwIfNotFound: true);
    }

    ~@Movimientos_Peleador()
    {
        UnityEngine.Debug.Assert(!m_Jugador1.enabled, "This will cause a leak and performance issues, Movimientos_Peleador.Jugador1.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Jugador2.enabled, "This will cause a leak and performance issues, Movimientos_Peleador.Jugador2.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jugador1
    private readonly InputActionMap m_Jugador1;
    private List<IJugador1Actions> m_Jugador1ActionsCallbackInterfaces = new List<IJugador1Actions>();
    private readonly InputAction m_Jugador1_Mover;
    private readonly InputAction m_Jugador1_Saltar;
    private readonly InputAction m_Jugador1_GolpeGanchoArriba;
    private readonly InputAction m_Jugador1_GolpeBajo;
    private readonly InputAction m_Jugador1_Bloquear;
    private readonly InputAction m_Jugador1_PatadaVoladoraCombo;
    private readonly InputAction m_Jugador1_PatadaconSalto;
    private readonly InputAction m_Jugador1_AmagueyPatada;
    private readonly InputAction m_Jugador1_AmagueyPatadaAvanzada;
    private readonly InputAction m_Jugador1_PatadaalaCabeza;
    private readonly InputAction m_Jugador1_GanchoDerecho;
    private readonly InputAction m_Jugador1_GolpesdeRodillaCombo;
    private readonly InputAction m_Jugador1_Fireball;
    /// <summary>
    /// Provides access to input actions defined in input action map "Jugador1".
    /// </summary>
    public struct Jugador1Actions
    {
        private @Movimientos_Peleador m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Jugador1Actions(@Movimientos_Peleador wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/Mover".
        /// </summary>
        public InputAction @Mover => m_Wrapper.m_Jugador1_Mover;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/Saltar".
        /// </summary>
        public InputAction @Saltar => m_Wrapper.m_Jugador1_Saltar;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/GolpeGanchoArriba".
        /// </summary>
        public InputAction @GolpeGanchoArriba => m_Wrapper.m_Jugador1_GolpeGanchoArriba;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/GolpeBajo".
        /// </summary>
        public InputAction @GolpeBajo => m_Wrapper.m_Jugador1_GolpeBajo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/Bloquear".
        /// </summary>
        public InputAction @Bloquear => m_Wrapper.m_Jugador1_Bloquear;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/PatadaVoladoraCombo".
        /// </summary>
        public InputAction @PatadaVoladoraCombo => m_Wrapper.m_Jugador1_PatadaVoladoraCombo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/PatadaconSalto".
        /// </summary>
        public InputAction @PatadaconSalto => m_Wrapper.m_Jugador1_PatadaconSalto;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/AmagueyPatada".
        /// </summary>
        public InputAction @AmagueyPatada => m_Wrapper.m_Jugador1_AmagueyPatada;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/AmagueyPatadaAvanzada".
        /// </summary>
        public InputAction @AmagueyPatadaAvanzada => m_Wrapper.m_Jugador1_AmagueyPatadaAvanzada;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/PatadaalaCabeza".
        /// </summary>
        public InputAction @PatadaalaCabeza => m_Wrapper.m_Jugador1_PatadaalaCabeza;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/GanchoDerecho".
        /// </summary>
        public InputAction @GanchoDerecho => m_Wrapper.m_Jugador1_GanchoDerecho;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/GolpesdeRodillaCombo".
        /// </summary>
        public InputAction @GolpesdeRodillaCombo => m_Wrapper.m_Jugador1_GolpesdeRodillaCombo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador1/Fireball".
        /// </summary>
        public InputAction @Fireball => m_Wrapper.m_Jugador1_Fireball;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Jugador1; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Jugador1Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Jugador1Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Jugador1Actions" />
        public void AddCallbacks(IJugador1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Jugador1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Jugador1ActionsCallbackInterfaces.Add(instance);
            @Mover.started += instance.OnMover;
            @Mover.performed += instance.OnMover;
            @Mover.canceled += instance.OnMover;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @GolpeGanchoArriba.started += instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.performed += instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.canceled += instance.OnGolpeGanchoArriba;
            @GolpeBajo.started += instance.OnGolpeBajo;
            @GolpeBajo.performed += instance.OnGolpeBajo;
            @GolpeBajo.canceled += instance.OnGolpeBajo;
            @Bloquear.started += instance.OnBloquear;
            @Bloquear.performed += instance.OnBloquear;
            @Bloquear.canceled += instance.OnBloquear;
            @PatadaVoladoraCombo.started += instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.performed += instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.canceled += instance.OnPatadaVoladoraCombo;
            @PatadaconSalto.started += instance.OnPatadaconSalto;
            @PatadaconSalto.performed += instance.OnPatadaconSalto;
            @PatadaconSalto.canceled += instance.OnPatadaconSalto;
            @AmagueyPatada.started += instance.OnAmagueyPatada;
            @AmagueyPatada.performed += instance.OnAmagueyPatada;
            @AmagueyPatada.canceled += instance.OnAmagueyPatada;
            @AmagueyPatadaAvanzada.started += instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.performed += instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.canceled += instance.OnAmagueyPatadaAvanzada;
            @PatadaalaCabeza.started += instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.performed += instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.canceled += instance.OnPatadaalaCabeza;
            @GanchoDerecho.started += instance.OnGanchoDerecho;
            @GanchoDerecho.performed += instance.OnGanchoDerecho;
            @GanchoDerecho.canceled += instance.OnGanchoDerecho;
            @GolpesdeRodillaCombo.started += instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.performed += instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.canceled += instance.OnGolpesdeRodillaCombo;
            @Fireball.started += instance.OnFireball;
            @Fireball.performed += instance.OnFireball;
            @Fireball.canceled += instance.OnFireball;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Jugador1Actions" />
        private void UnregisterCallbacks(IJugador1Actions instance)
        {
            @Mover.started -= instance.OnMover;
            @Mover.performed -= instance.OnMover;
            @Mover.canceled -= instance.OnMover;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @GolpeGanchoArriba.started -= instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.performed -= instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.canceled -= instance.OnGolpeGanchoArriba;
            @GolpeBajo.started -= instance.OnGolpeBajo;
            @GolpeBajo.performed -= instance.OnGolpeBajo;
            @GolpeBajo.canceled -= instance.OnGolpeBajo;
            @Bloquear.started -= instance.OnBloquear;
            @Bloquear.performed -= instance.OnBloquear;
            @Bloquear.canceled -= instance.OnBloquear;
            @PatadaVoladoraCombo.started -= instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.performed -= instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.canceled -= instance.OnPatadaVoladoraCombo;
            @PatadaconSalto.started -= instance.OnPatadaconSalto;
            @PatadaconSalto.performed -= instance.OnPatadaconSalto;
            @PatadaconSalto.canceled -= instance.OnPatadaconSalto;
            @AmagueyPatada.started -= instance.OnAmagueyPatada;
            @AmagueyPatada.performed -= instance.OnAmagueyPatada;
            @AmagueyPatada.canceled -= instance.OnAmagueyPatada;
            @AmagueyPatadaAvanzada.started -= instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.performed -= instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.canceled -= instance.OnAmagueyPatadaAvanzada;
            @PatadaalaCabeza.started -= instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.performed -= instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.canceled -= instance.OnPatadaalaCabeza;
            @GanchoDerecho.started -= instance.OnGanchoDerecho;
            @GanchoDerecho.performed -= instance.OnGanchoDerecho;
            @GanchoDerecho.canceled -= instance.OnGanchoDerecho;
            @GolpesdeRodillaCombo.started -= instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.performed -= instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.canceled -= instance.OnGolpesdeRodillaCombo;
            @Fireball.started -= instance.OnFireball;
            @Fireball.performed -= instance.OnFireball;
            @Fireball.canceled -= instance.OnFireball;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Jugador1Actions.UnregisterCallbacks(IJugador1Actions)" />.
        /// </summary>
        /// <seealso cref="Jugador1Actions.UnregisterCallbacks(IJugador1Actions)" />
        public void RemoveCallbacks(IJugador1Actions instance)
        {
            if (m_Wrapper.m_Jugador1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Jugador1Actions.AddCallbacks(IJugador1Actions)" />
        /// <seealso cref="Jugador1Actions.RemoveCallbacks(IJugador1Actions)" />
        /// <seealso cref="Jugador1Actions.UnregisterCallbacks(IJugador1Actions)" />
        public void SetCallbacks(IJugador1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Jugador1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Jugador1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Jugador1Actions" /> instance referencing this action map.
    /// </summary>
    public Jugador1Actions @Jugador1 => new Jugador1Actions(this);

    // Jugador2
    private readonly InputActionMap m_Jugador2;
    private List<IJugador2Actions> m_Jugador2ActionsCallbackInterfaces = new List<IJugador2Actions>();
    private readonly InputAction m_Jugador2_Mover;
    private readonly InputAction m_Jugador2_Saltar;
    private readonly InputAction m_Jugador2_GolpeGanchoArriba;
    private readonly InputAction m_Jugador2_GolpeBajo;
    private readonly InputAction m_Jugador2_Bloquear;
    private readonly InputAction m_Jugador2_PatadaVoladoraCombo;
    private readonly InputAction m_Jugador2_PatadaconSalto;
    private readonly InputAction m_Jugador2_AmagueyPatada;
    private readonly InputAction m_Jugador2_AmagueyPatadaAvanzada;
    private readonly InputAction m_Jugador2_PatadaalaCabeza;
    private readonly InputAction m_Jugador2_GanchoDerecho;
    private readonly InputAction m_Jugador2_GolpesdeRodillaCombo;
    private readonly InputAction m_Jugador2_Fireball;
    /// <summary>
    /// Provides access to input actions defined in input action map "Jugador2".
    /// </summary>
    public struct Jugador2Actions
    {
        private @Movimientos_Peleador m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Jugador2Actions(@Movimientos_Peleador wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/Mover".
        /// </summary>
        public InputAction @Mover => m_Wrapper.m_Jugador2_Mover;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/Saltar".
        /// </summary>
        public InputAction @Saltar => m_Wrapper.m_Jugador2_Saltar;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/GolpeGanchoArriba".
        /// </summary>
        public InputAction @GolpeGanchoArriba => m_Wrapper.m_Jugador2_GolpeGanchoArriba;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/GolpeBajo".
        /// </summary>
        public InputAction @GolpeBajo => m_Wrapper.m_Jugador2_GolpeBajo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/Bloquear".
        /// </summary>
        public InputAction @Bloquear => m_Wrapper.m_Jugador2_Bloquear;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/PatadaVoladoraCombo".
        /// </summary>
        public InputAction @PatadaVoladoraCombo => m_Wrapper.m_Jugador2_PatadaVoladoraCombo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/PatadaconSalto".
        /// </summary>
        public InputAction @PatadaconSalto => m_Wrapper.m_Jugador2_PatadaconSalto;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/AmagueyPatada".
        /// </summary>
        public InputAction @AmagueyPatada => m_Wrapper.m_Jugador2_AmagueyPatada;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/AmagueyPatadaAvanzada".
        /// </summary>
        public InputAction @AmagueyPatadaAvanzada => m_Wrapper.m_Jugador2_AmagueyPatadaAvanzada;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/PatadaalaCabeza".
        /// </summary>
        public InputAction @PatadaalaCabeza => m_Wrapper.m_Jugador2_PatadaalaCabeza;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/GanchoDerecho".
        /// </summary>
        public InputAction @GanchoDerecho => m_Wrapper.m_Jugador2_GanchoDerecho;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/GolpesdeRodillaCombo".
        /// </summary>
        public InputAction @GolpesdeRodillaCombo => m_Wrapper.m_Jugador2_GolpesdeRodillaCombo;
        /// <summary>
        /// Provides access to the underlying input action "Jugador2/Fireball".
        /// </summary>
        public InputAction @Fireball => m_Wrapper.m_Jugador2_Fireball;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Jugador2; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Jugador2Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Jugador2Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Jugador2Actions" />
        public void AddCallbacks(IJugador2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Jugador2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Jugador2ActionsCallbackInterfaces.Add(instance);
            @Mover.started += instance.OnMover;
            @Mover.performed += instance.OnMover;
            @Mover.canceled += instance.OnMover;
            @Saltar.started += instance.OnSaltar;
            @Saltar.performed += instance.OnSaltar;
            @Saltar.canceled += instance.OnSaltar;
            @GolpeGanchoArriba.started += instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.performed += instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.canceled += instance.OnGolpeGanchoArriba;
            @GolpeBajo.started += instance.OnGolpeBajo;
            @GolpeBajo.performed += instance.OnGolpeBajo;
            @GolpeBajo.canceled += instance.OnGolpeBajo;
            @Bloquear.started += instance.OnBloquear;
            @Bloquear.performed += instance.OnBloquear;
            @Bloquear.canceled += instance.OnBloquear;
            @PatadaVoladoraCombo.started += instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.performed += instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.canceled += instance.OnPatadaVoladoraCombo;
            @PatadaconSalto.started += instance.OnPatadaconSalto;
            @PatadaconSalto.performed += instance.OnPatadaconSalto;
            @PatadaconSalto.canceled += instance.OnPatadaconSalto;
            @AmagueyPatada.started += instance.OnAmagueyPatada;
            @AmagueyPatada.performed += instance.OnAmagueyPatada;
            @AmagueyPatada.canceled += instance.OnAmagueyPatada;
            @AmagueyPatadaAvanzada.started += instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.performed += instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.canceled += instance.OnAmagueyPatadaAvanzada;
            @PatadaalaCabeza.started += instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.performed += instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.canceled += instance.OnPatadaalaCabeza;
            @GanchoDerecho.started += instance.OnGanchoDerecho;
            @GanchoDerecho.performed += instance.OnGanchoDerecho;
            @GanchoDerecho.canceled += instance.OnGanchoDerecho;
            @GolpesdeRodillaCombo.started += instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.performed += instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.canceled += instance.OnGolpesdeRodillaCombo;
            @Fireball.started += instance.OnFireball;
            @Fireball.performed += instance.OnFireball;
            @Fireball.canceled += instance.OnFireball;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Jugador2Actions" />
        private void UnregisterCallbacks(IJugador2Actions instance)
        {
            @Mover.started -= instance.OnMover;
            @Mover.performed -= instance.OnMover;
            @Mover.canceled -= instance.OnMover;
            @Saltar.started -= instance.OnSaltar;
            @Saltar.performed -= instance.OnSaltar;
            @Saltar.canceled -= instance.OnSaltar;
            @GolpeGanchoArriba.started -= instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.performed -= instance.OnGolpeGanchoArriba;
            @GolpeGanchoArriba.canceled -= instance.OnGolpeGanchoArriba;
            @GolpeBajo.started -= instance.OnGolpeBajo;
            @GolpeBajo.performed -= instance.OnGolpeBajo;
            @GolpeBajo.canceled -= instance.OnGolpeBajo;
            @Bloquear.started -= instance.OnBloquear;
            @Bloquear.performed -= instance.OnBloquear;
            @Bloquear.canceled -= instance.OnBloquear;
            @PatadaVoladoraCombo.started -= instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.performed -= instance.OnPatadaVoladoraCombo;
            @PatadaVoladoraCombo.canceled -= instance.OnPatadaVoladoraCombo;
            @PatadaconSalto.started -= instance.OnPatadaconSalto;
            @PatadaconSalto.performed -= instance.OnPatadaconSalto;
            @PatadaconSalto.canceled -= instance.OnPatadaconSalto;
            @AmagueyPatada.started -= instance.OnAmagueyPatada;
            @AmagueyPatada.performed -= instance.OnAmagueyPatada;
            @AmagueyPatada.canceled -= instance.OnAmagueyPatada;
            @AmagueyPatadaAvanzada.started -= instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.performed -= instance.OnAmagueyPatadaAvanzada;
            @AmagueyPatadaAvanzada.canceled -= instance.OnAmagueyPatadaAvanzada;
            @PatadaalaCabeza.started -= instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.performed -= instance.OnPatadaalaCabeza;
            @PatadaalaCabeza.canceled -= instance.OnPatadaalaCabeza;
            @GanchoDerecho.started -= instance.OnGanchoDerecho;
            @GanchoDerecho.performed -= instance.OnGanchoDerecho;
            @GanchoDerecho.canceled -= instance.OnGanchoDerecho;
            @GolpesdeRodillaCombo.started -= instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.performed -= instance.OnGolpesdeRodillaCombo;
            @GolpesdeRodillaCombo.canceled -= instance.OnGolpesdeRodillaCombo;
            @Fireball.started -= instance.OnFireball;
            @Fireball.performed -= instance.OnFireball;
            @Fireball.canceled -= instance.OnFireball;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Jugador2Actions.UnregisterCallbacks(IJugador2Actions)" />.
        /// </summary>
        /// <seealso cref="Jugador2Actions.UnregisterCallbacks(IJugador2Actions)" />
        public void RemoveCallbacks(IJugador2Actions instance)
        {
            if (m_Wrapper.m_Jugador2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Jugador2Actions.AddCallbacks(IJugador2Actions)" />
        /// <seealso cref="Jugador2Actions.RemoveCallbacks(IJugador2Actions)" />
        /// <seealso cref="Jugador2Actions.UnregisterCallbacks(IJugador2Actions)" />
        public void SetCallbacks(IJugador2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Jugador2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Jugador2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Jugador2Actions" /> instance referencing this action map.
    /// </summary>
    public Jugador2Actions @Jugador2 => new Jugador2Actions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Jugador1" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Jugador1Actions.AddCallbacks(IJugador1Actions)" />
    /// <seealso cref="Jugador1Actions.RemoveCallbacks(IJugador1Actions)" />
    public interface IJugador1Actions
    {
        /// <summary>
        /// Method invoked when associated input action "Mover" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMover(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Saltar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSaltar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpe Gancho Arriba" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpeGanchoArriba(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpe Bajo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpeBajo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bloquear" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBloquear(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada Voladora Combo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaVoladoraCombo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada con Salto" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaconSalto(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Amague y Patada" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAmagueyPatada(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Amague y Patada Avanzada" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAmagueyPatadaAvanzada(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada a la Cabeza" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaalaCabeza(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Gancho Derecho" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGanchoDerecho(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpes de Rodilla Combo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpesdeRodillaCombo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Fireball" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFireball(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Jugador2" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Jugador2Actions.AddCallbacks(IJugador2Actions)" />
    /// <seealso cref="Jugador2Actions.RemoveCallbacks(IJugador2Actions)" />
    public interface IJugador2Actions
    {
        /// <summary>
        /// Method invoked when associated input action "Mover" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMover(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Saltar" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSaltar(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpe Gancho Arriba" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpeGanchoArriba(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpe Bajo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpeBajo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Bloquear" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBloquear(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada Voladora Combo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaVoladoraCombo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada con Salto" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaconSalto(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Amague y Patada" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAmagueyPatada(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Amague y Patada Avanzada" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnAmagueyPatadaAvanzada(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Patada a la Cabeza" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPatadaalaCabeza(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Gancho Derecho" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGanchoDerecho(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Golpes de Rodilla Combo" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnGolpesdeRodillaCombo(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Fireball" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFireball(InputAction.CallbackContext context);
    }
}
